struct MyPokemon **PlayerSwitchSave;
struct MyPokemon **EnemySwitchSave;
struct MyPokemon **Temp;
bool StatCalc = 1;
bool BattleMode = 0;
bool Retrieve = 0;
bool Execute = 0;
bool Reset = 0;
bool First = 0;
bool Display = 0;
bool PlayerSwitch = 0;
bool EnemySwitch = 0;
bool PlayerHit = 0;
bool EnemyHit = 0;
char x[32];
int Damage;
int EnemyDamage;
float STAB;
float EnemySTAB;